services:
  fr3_vision_sorting:
    build:
      context: .
      dockerfile: Dockerfile
    image: fr3-vision-sorting:jazzy
    container_name: fr3_vision_sorting

    network_mode: host
    ipc: host
    privileged: true

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}

    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb

    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash
